/*
 * This file is generated by jOOQ.
 */
package org.acme.model;


import org.acme.model.tables.Pessoas;
import org.acme.model.tables.records.PessoasRecord;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.Internal;


/**
 * A class modelling foreign key relationships and constraints of tables in
 * public.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Keys {

    // -------------------------------------------------------------------------
    // UNIQUE and PRIMARY KEY definitions
    // -------------------------------------------------------------------------

    public static final UniqueKey<PessoasRecord> PESSOAS_APELIDO_KEY = Internal.createUniqueKey(Pessoas.PESSOAS, DSL.name("PESSOAS_APELIDO_key"), new TableField[] { Pessoas.PESSOAS.APELIDO }, true);
    public static final UniqueKey<PessoasRecord> PESSOAS_PKEY = Internal.createUniqueKey(Pessoas.PESSOAS, DSL.name("PESSOAS_pkey"), new TableField[] { Pessoas.PESSOAS.ID }, true);
}
