/*
 * This file is generated by jOOQ.
 */
package org.acme.model;


import org.acme.model.tables.Pessoas;


/**
 * Convenience access to all tables in public.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

    /**
     * The table <code>public.PESSOAS</code>.
     */
    public static final Pessoas PESSOAS = Pessoas.PESSOAS;
}
